FROM golang:latest as build-env
RUN mkdir /build
ADD . /build/
WORKDIR /build
# static build is required
ENV CGO_ENABLED=0
RUN make dbadmin

FROM alpine
WORKDIR /app/
COPY --from=build-env /build/bin/dbadmin .
CMD ["/app/dbadmin"]

EXPOSE 7777
