apiVersion: v1
kind: Secret
metadata:
  name: envoy-config
type: Opaque
stringData:
  envoy.yaml: |-
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9900
      access_log_path: /tmp/admin_access.log

    node:
      cluster: service_greeter
      id: erbs

    dynamic_resources:
      lds_config:
        resource_api_version: V3
        api_config_source:
          api_type: GRPC
          transport_api_version: V3
          grpc_services:
            envoy_grpc:
              cluster_name: xds_cluster
          set_node_on_first_message_only: true

      cds_config:
        resource_api_version: V3
        api_config_source:
          api_type: GRPC
          transport_api_version: V3
          grpc_services:
            envoy_grpc:
              cluster_name: xds_cluster
          set_node_on_first_message_only: true

    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 0.5s
        type: strict_dns
        lb_policy: ROUND_ROBIN
        http2_protocol_options: {}
        upstream_connection_options:
          # configure a TCP keep-alive to detect and reconnect to the admin
          # server in the event of a TCP socket half open connection
          tcp_keepalive: {}
        load_assignment:
          cluster_name: xds_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: controlplane
                    port_value: 9901

      - name: authentication
        type: strict_dns
        dns_lookup_family: v4_only
        connect_timeout: 0.5s
        http2_protocol_options: {}
        upstream_connection_options:
          # configure a TCP keep-alive to detect and reconnect to the admin
          # server in the event of a TCP socket half open connection
          tcp_keepalive: {}
        load_assignment:
          cluster_name: authentication
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: authserver
                    port_value: 4000

      - name: accesslog
        type: strict_dns
        dns_lookup_family: v4_only
        connect_timeout: 0.5s
        http2_protocol_options: {}
        upstream_connection_options:
          # configure a TCP keep-alive to detect and reconnect to the admin
          # server in the event of a TCP socket half open connection
          tcp_keepalive: {}
        load_assignment:
          cluster_name: accesslog
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: accesslogserver
                    port_value: 6001

      - name: ratelimiter
        type: strict_dns
        dns_lookup_family: v4_only
        connect_timeout: 0.5s
        http2_protocol_options: {}
        upstream_connection_options:
          # configure a TCP keep-alive to detect and reconnect to the admin
          # server in the event of a TCP socket half open connection
          tcp_keepalive: {}
        load_assignment:
          cluster_name: ratelimiter
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ratelimiter
                    port_value: 5000
