---
apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  selector:
    app: envoy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: envoyproxy-http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: envoyproxy-https
    - protocol: TCP
      port: 9900
      targetPort: 9900
      name: envoy-admin
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local
