apiVersion: v1
kind: Secret
metadata:
  name: controlplane-config
type: Opaque
stringData:
  controlplane-config.yaml: |-

    logger:
      level: debug
      filename: /dev/stdout

    webadmin:
      listen: 0.0.0.0:9902
      ipacl: 0.0.0.0/0
      logger:
        level: debug
        filename: /dev/stdout

{{- if .Values.global.useLocalCassandra }}
    database:
      hostname: {{ .Release.Namespace }}-cassandra.{{ .Release.Namespace }}
      port: 9042
      tls:
        enable: false
        capath: ""
      username: cassandra
      password: password # In <useLocalCassandra> mode the secret of local Cassandra will be mounted directly to pod.
      keyspace: gatekeeper
      initkeyspaces: false # let auth server create tables for us
      timeout: 30s
      connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to start up.
      queryretries: 0
{{- end }}

    xds:
      listen: 0.0.0.0:9901
      configcompileinterval: 2s
      cluster: controlplane
      timeout: 2s
