---
apiVersion: v1
kind: Service
metadata:
  name: controlplane
spec:
  selector:
    app: controlplane
  ports:
    - protocol: TCP
      port: 9901
      targetPort: 9901
      name: xds-grpc
    - protocol: TCP
      port: 9902
      targetPort: 9902
      name: webadmin
    - protocol: TCP
      port: 9903
      targetPort: 9003
      name: xds-http
  type: ClusterIP
