---
apiVersion: v1
kind: Secret
metadata:
  name: authserver-config
type: Opaque
stringData:
  authserver-config.yaml: |-

      # Authserver authentication daemon settings
      #
      logger:
        level: debug
        filename: /dev/stdout
        maxsize: 0
        maxage: 0
        maxbackups: 0

      # The address to listen on for Admin UI
      webadmin:
        logger:
          level: debug
          filename: /dev/stdout
          maxsize: 0
          maxage: 0
          maxbackups: 0
        listen: 0.0.0.0:2113
        ipacl: 0.0.0.0/0
        tls:
          certfile: ""
          keyfile: ""

      # The address to listen on for GRPC requests coming from Envoy
      envoyauth:
        listen: 0.0.0.0:4000

      # public endpoint for oauth requests
      oauth:
        logger:
          level: debug
          filename: /dev/stdout
          maxsize: 0
          maxage: 0
          maxbackups: 0
        listen: 0.0.0.0:4001
        tls: {}
        tokenissuepath: /oauth2/token
        tokeninfopath: /oauth2/info

{{- if .Values.global.useLocalCassandra }}
      database:
        hostname: {{ .Release.Namespace }}-cassandra.{{ .Release.Namespace }}
        port: 9042
        tls:
          enable: false
          capath: ""
        username: cassandra
        password: password # In <useLocalCassandra> mode the secret of local Cassandra will be mounted directly to pod.
        keyspace: gatekeeper
        initkeyspaces: true
        timeout: 30s
        connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to start up.
        queryretries: 0
{{- end }}

      cache:
        size: 50000           # cache size in bytes
        ttl: 60               # cache ttl for positive hits
        negativettl: 15       # cache ttl for failed lookups

      geoip:
        database: ""
