---
apiVersion: v1
kind: Service
metadata:
  name: authserver
spec:
  selector:
    app: authserver
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: auth-grpc
    - protocol: TCP
      port: 2113
      targetPort: 2113
      name: auth-webadmin
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local
