# Example REST calls for apiproduct


### Get all apiproducts
GET http://{{hostname}}/v1/apiproducts


### Get one apiproduct
GET http://{{hostname}}/v1/apiproducts/people


### Create a new api product
POST http://{{hostname}}/v1/apiproducts
content-type: application/json

{
    "name": "people",
    "displayName": "People Inc",
    "routeGroup": "routes_443",
    "paths": [
        "/people/*"
    ]
}


### Update an apiproduct
POST http://{{hostname}}/v1/apiproducts/people
content-type: application/json

{
    "name": "people",
    "displayName": "People Inc",
    "routeGroup": "routes_443",
    "paths": [
        "/people",
        "/people/1",
        "/people/*"
    ],
    "attributes": [
    {
        "name": "people_quotaPerSecond",
        "value": "42"
    },
    {
        "name": "OpeningHours",
        "value": "9-5"
    }
    ],
    "policies": "burp,checkIPAccessList,checkReferer,qps,sendAPIKey,sendDeveloperEmail,sendDeveloperID,sendDeveloperAppID"
}


###
DELETE http://{{hostname}}/v1/apiproducts/people
