# Authserver authentication daemon settings
#
logger:
  level: debug
  filename: /dev/stdout

# The address to listen on for Admin UI
webadmin:
  logger:
    level: debug
    filename: /dev/stdout
  listen: 0.0.0.0:2113
  ipacl: 0.0.0.0/0

# The address to listen on for GRPC requests coming from Envoy
envoyauth:
  listen: 0.0.0.0:4000

# public endpoint for oauth requests
oauth:
  logger:
    level: debug
    filename: /dev/stdout
  listen: 0.0.0.0:4001
  tokenissuepath: /oauth2/token
  tokeninfopath: /oauth2/info

database:
  hostname: cassandra
  port: 9042
  tls:
    enable: false
  username: cassandra
  password: password
  keyspace: gatekeeper
  initkeyspaces: true
  timeout: 30s
  connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to start up.
  queryretries: 0
  cassandratype: oss # must be oss or cosmosdb

cache:
  size: 50000         # cache size in bytes
  ttl: 60               # cache ttl for positive hits
  negativettl: 15       # cache ttl for failed lookups

geoip:
  database: ""
