# Envoy control plane daemon settings

logger:
  level: info
  filename: controlplane-admin.log

webadmin:
  listen: 0.0.0.0:9902
  ipacl: 0.0.0.0/0
  logger:
    level: info
    filename: controlplane-access.log

# Cassandra settings
database:
  hostname: cassandra
  port: 9042
  tls:
    enable: false
  username: cassandra
  password: cassandra
  keyspace: gatekeeper
  timeout: 2s
  connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to initialize database in case of a fresh install.

xds:
  listen: 0.0.0.0:9901
  configcompileinterval: 2s
  cluster: controlplane
  timeout: 2s
