# from https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listener:
              example_listener_name:
                connection_limit: 10000
        overload:
          global_downstream_max_connections: 50000

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9900
  access_log_path: /tmp/admin_access.log

node:
  cluster: service_greeter
  id: jenny

dynamic_resources:
  lds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        envoy_grpc:
          cluster_name: controlplane
      set_node_on_first_message_only: true

  cds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        envoy_grpc:
          cluster_name: controlplane
      set_node_on_first_message_only: true

static_resources:
  clusters:
  - name: controlplane
    connect_timeout: 1s
    type: STRICT_DNS
    http2_protocol_options: {}
    common_http_protocol_options:
      idle_timeout:
        seconds: 15
    upstream_connection_options:
      tcp_keepalive:
        keepalive_probes: 3
        keepalive_time: 10
        keepalive_interval: 10
    load_assignment:
      cluster_name: controlplane
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: controlplane
                port_value: 9901

  - name: authserver
    type: STRICT_DNS
    connect_timeout: 1s
    http2_protocol_options: {}
    common_http_protocol_options:
      idle_timeout:
        seconds: 15
    upstream_connection_options:
      tcp_keepalive:
        keepalive_probes: 3
        keepalive_time: 10
        keepalive_interval: 10
    load_assignment:
      cluster_name: authserver
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: authserver
                port_value: 4000

  - name: accesslogserver
    type: STRICT_DNS
    connect_timeout: 1s
    http2_protocol_options: {}
    common_http_protocol_options:
      idle_timeout:
        seconds: 15
    upstream_connection_options:
      tcp_keepalive:
        keepalive_probes: 3
        keepalive_time: 10
        keepalive_interval: 10
    load_assignment:
      cluster_name: accesslogserver
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: authserver
                port_value: 6001
