# Envoy control plane daemon settings

logging:
  level: info
  filename: envoycp-admin.log

webadmin:
  listen: 0.0.0.0:9902
  ipacl: 0.0.0.0/0
  logging:
    level: info
    filename: envoycp-access.log

# Cassandra settings
database:
  hostname: cassandra
  port: 9042
  tls:
    enable: false
  username: cassandra
  password: cassandra
  keyspace: gatekeeper
  timeout: 2s
  connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to start up.

xds:
  grpclisten: 0.0.0.0:9901
  configcompileinterval: 2s
  cluster: envoycp
  timeout: 2s

envoyproxy:
  extauthz:
    enable: true
    cluster: envoyauth
    timeout: 0.5s
    failuremodeallow: true
    requestbodysize: 512
