version: "3.8"

services:
  cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - /tmp/cassandra_data:/var/lib/cassandra

  managementserver:
    image: gatekeeper/managementserver:latest
    container_name: managementserver
    entrypoint: ["/app/managementserver", "--config", "/config/managementserver.yaml", "--createschema", "--replicacount=1"]
    secrets:
      - source: managementserver-config
        target: /config/managementserver.yaml
    ports:
      - 7777:7777
    restart: unless-stopped

  accesslogserver:
    image: gatekeeper/accesslogserver:latest
    container_name: accesslogserver
    entrypoint: ["/app/accesslogserver", "--config", "/config/accesslogserver.yaml"]
    secrets:
      - source: accesslogserver-config
        target: /config/accesslogserver.yaml
    ports:
      - 6001-6002:6001-6002
    restart: unless-stopped

  authserver:
    image: gatekeeper/authserver:latest
    container_name: authserver
    entrypoint: ["/app/authserver", "--config", "/config/authserver.yaml"]
    secrets:
      - source: authserver-config
        target: /config/authserver.yaml
    ports:
      - 2113:2113
      - 4000-4001:4001-4001
    restart: unless-stopped

  controlplane:
    image: gatekeeper/controlplane:latest
    container_name: controlplane
    entrypoint: ["/app/controlplane", "--config", "/config/controlplane.yaml"]
    secrets:
      - source: controlplane-config
        target: /config/controlplane.yaml
    ports:
      - 9901-9903:9901-9903
    restart: unless-stopped

  envoyproxy:
    image: envoyproxy/envoy-alpine:v1.17-latest
    container_name: envoyproxy
    entrypoint: ["/usr/local/bin/envoy", "-c", "/config/envoyproxy.yaml"]
    secrets:
      - source: envoyproxy-config
        target: /config/envoyproxy.yaml
    ports:
      - 80:80
      - 443:443
      - 9900:9900
    restart: unless-stopped

secrets:
  managementserver-config:
    file: managementserver.yaml
  authserver-config:
    file: authserver.yaml
  accesslogserver-config:
    file: accesslogserver.yaml
  controlplane-config:
    file: controlplane.yaml
  envoyproxy-config:
    file: envoyproxy.yaml
