# managementserver daemon settings
#
logger:
  level: debug
  filename: /dev/stdout

# The address to listen on for REST API
webadmin:
  listen: 0.0.0.0:7777
  ipacl: 0.0.0.0/0
  logger:
    level: debug
    filename: /dev/stdout

database:
  hostname: cassandra
  port: 9042
  tls:
    enable: false
  username: cassandra
  password: password
  keyspace: gatekeeper
  timeout: 2s
  connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to start up.

audit:
  logger:
    level: debug
    filename: /dev/stdout

  database:
    hostname: cassandra
    port: 9042
    tls:
      enable: false
    username: cassandra
    password: password
    keyspace: gatekeeper
    timeout: 20s
  