# Envoy control plane daemon settings

loglevel: info

webadmin:
  listen: 0.0.0.0:9902
  ipacl: 0.0.0.0/0
  logfile: envoycp-admin.log

# Cassandra settings
database:
  hostname: cassandra
  port: 9042
  tls:
    enable: false
  username: cassandra
  password: cassandra
  keyspace: gatekeeper
  timeout: 2s
  connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to start up.

xds:
  grpclisten: 0.0.0.0:9901
  httplisten: 0.0.0.0:9903

  configpushinterval: 2s

  envoy:
    extauthz:
      enabled: true
      cluster: envoyauth
      timeout: 0.5s
      failuremodeallow: true
      requestbodysize: 512

    logging:
      # grpc:
      #   logname: httplog
      #   cluster: logreceiver
      #   timeout: 5s
      #   buffersize: 10485760
      file:
        logfilename: /dev/stdout
        fields:
          request_id: '%REQ(REQUEST-ID)%'
          start_time: '%START_TIME%'
          caller: '%REQ(CALLER)%'
          request_method: '%REQ(:METHOD)%'
          request_path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
          content_type: '%REQ(CONTENT-TYPE)%'
          protocol: '%PROTOCOL%'
          response_code: '%RESPONSE_CODE%'
          response_flags: '%RESPONSE_FLAGS%'
          bytes_sent: '%BYTES_SENT%'
          bytes_received: '%BYTES_RECEIVED%'
          request_duration: '%DURATION%'
          response_duration: '%RESPONSE_DURATION%'
          upstream_response_time: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
          client_address: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
          x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
          user_agent: '%REQ(USER-AGENT)%'
          http2_authority: '%REQ(:AUTHORITY)%'
          upstream_cluster: '%UPSTREAM_CLUSTER%'
          upstream_host: '%UPSTREAM_HOST%'
          route_name: '%ROUTE_NAME%'
          upstream_transport_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'
          downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
          method: '%REQ(:METHOD)%'
          path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
