version: "3.8"

services:
  cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - /tmp/cassandra_data:/var/lib/cassandra

  dbadmin:
    image: gatekeeper/dbadmin:latest
    container_name: dbadmin
    entrypoint: ["/app/dbadmin", "--config", "/config/dbadmin.yaml", "--createschema", "--replicacount=1"]
    secrets:
      - source: dbadmin-config
        target: /config/dbadmin.yaml
    ports:
      - 7777:7777
    restart: unless-stopped

  envoyauth:
    image: gatekeeper/envoyauth:latest
    container_name: envoyauth
    entrypoint: ["/app/envoyauth", "--config", "/config/envoyauth.yaml"]
    secrets:
      - source: envoyauth-config
        target: /config/envoyauth.yaml
    ports:
      - 2113:2113
      - 4000-4001:4001-4001
    restart: unless-stopped

  envoycp:
    image: gatekeeper/envoycp:latest
    container_name: envoycp
    entrypoint: ["/app/envoycp", "--config", "/config/envoycp.yaml"]
    secrets:
      - source: envoycp-config
        target: /config/envoycp.yaml
    ports:
      - 9901-9903:9901-9903
    restart: unless-stopped

  envoyproxy:
    image: envoyproxy/envoy-alpine-dev:latest
    container_name: envoyproxy
    entrypoint: ["/usr/local/bin/envoy", "-c", "/config/envoyproxy.yaml"]
    secrets:
      - source: envoyproxy-config
        target: /config/envoyproxy.yaml
    ports:
      - 80:80
      - 443:443
      - 9900:9900
    restart: unless-stopped

secrets:
  dbadmin-config:
    file: dbadmin.yaml
  envoyauth-config:
    file: envoyauth.yaml
  envoycp-config:
    file: envoycp.yaml
  envoyproxy-config:
    file: envoyproxy.yaml
