# REST API daemon settings
#
# The address to listen on for REST API
rest_api_listen: 0.0.0.0:3333

# Cassandra settings
database_hostname: xx.cassandra.cosmos.azure.com
database_port: 10350
database_username: xx
database_password: xx
database_keyspace: kms

