# DBAdmin daemon settings
#
# The address to listen on for REST API
webadminlisten: 0.0.0.0:3333

# Cassandra settings
database:
  hostname: xx.cassandra.cosmos.azure.com
  port: 10350
  username: xx
  password: xx
  keyspace: kms

