# DBAdmin daemon settings
#
# The address to listen on for REST API
webadmin:
  listen: 0.0.0.0:7777
  ipacl: 127.0.0.0/24
  logfile: dbadmin-access.log

# Cassandra settings
database:
  hostname: cassandra
  port: 9042
  tls:
    enable: disable
  username: cassandra
  password: cassandra
  keyspace: gatekeeper
  timeout: 2s
