# DBAdmin daemon settings
#
# The address to listen on for REST API
webadmin:
  listen: 0.0.0.0:7777
  ipacl: 127.0.0.0/24
  logfile: dbadmin-access.log

# Cassandra settings
database:
  hostname: xx.cassandra.cosmos.azure.com
  port: 10350
  username: x
  password: x
  keyspace: x
  timeout: 2s
  healthcheckinterval: 5s