# Envoyauth authentication daemon settings
#
loglevel: info
# The address to listen on for GRPC requests coming from Envoy
authgrpclisten: 0.0.0.0:4000

# public endpoint for oauth requests
oauth:
  listen: 0.0.0.0:4001

# The address to listen on for Admin UI
webadmin:
  listen: 0.0.0.0:2113
  ipacl: 127.0.0.0/24
  logfile: envoyauth-admin.log

# Cassandra settings
database:
  hostname: x.cassandra.cosmos.azure.com
  port: 10350
  username: x
  password: x
  keyspace: x
  timeout: 2s
  healthcheckinterval: 5s

cache:
# database memory cache in bytes
  size: 1048576
# cache ttl for positive hits
  ttl: 60
# cache ttl for failed lookups
  negativettl: 15

# maxmind geoip database filename
geoip:
  filename: GeoIP2-City.mmdb
