---
apiVersion: v1
kind: Service
metadata:
  name: accesslogserver
spec:
  selector:
    app: accesslogserver
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
      name: grpc
    - protocol: TCP
      port: 6002
      targetPort: 6002
      name: webadmin
  type: ClusterIP