---
apiVersion: v1
kind: Secret
metadata:
  name: managementserver-config
type: Opaque
stringData:
  managementserver-config.yaml: |-

    # managementserver daemon settings
    #
    logger:
      level: debug
      filename: /dev/stdout

    # The address to listen on for REST API
    webadmin:
      listen: 0.0.0.0:7777
      ipacl: 0.0.0.0/0
      logger:
        level: debug
        filename: /dev/stdout

{{- if .Values.global.useLocalCassandra }}
    database:
      hostname: {{ .Release.Namespace }}-cassandra.{{ .Release.Namespace }}
      port: 9042
      tls:
        enable: false
        capath: ""
      username: cassandra
      password: password # In <useLocalCassandra> mode the secret of local Cassandra will be mounted directly to pod.
      keyspace: gatekeeper
      timeout: 30s
      connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to start up.
      queryretries: 0
{{- end }}
      
    audit:
      logger:
        level: debug
        filename: /dev/stdout

{{- if .Values.global.useLocalCassandra }}
      database:
        hostname: {{ .Release.Namespace }}-cassandra.{{ .Release.Namespace }}
        port: 9042
        tls:
          enable: false
          capath: ""
        username: cassandra
        password: password # In <useLocalCassandra> mode the secret of local Cassandra will be mounted directly to pod.
        keyspace: gatekeeper
        timeout: 30s
        connectattempts: 20     # Will try up to 20 times to connect before giving up. This will allow Cassandra to start up.
        queryretries: 0
        cassandratype: oss # must be oss or cosmosdb
{{- end }}
