---
apiVersion: v1
kind: Service
metadata:
  name: managementserver
spec:
  selector:
    app: managementserver
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
