name: Build pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build containers

    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2

    - name: Build Docker images
      run: make docker-images

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: erikbos
        password: ${{ secrets.cr_pat }}

    - name: Docker tag & push
      run: |
       echo ${{ github.sha }}

       docker tag gatekeeper/managementserver:latest ghcr.io/erikbos/gatekeeper-managementserver
       docker tag gatekeeper/accesslogserver:latest ghcr.io/erikbos/gatekeeper-accesslogserver
       docker tag gatekeeper/authserver:latest ghcr.io/erikbos/gatekeeper-authserver
       docker tag gatekeeper/controlplane:latest ghcr.io/erikbos/gatekeeper-controlplane
       docker tag gatekeeper/testbackend:latest ghcr.io/erikbos/gatekeeper-testbackend

       docker push ghcr.io/erikbos/gatekeeper-managementserver
       docker push ghcr.io/erikbos/gatekeeper-accesslogserver
       docker push ghcr.io/erikbos/gatekeeper-authserver
       docker push ghcr.io/erikbos/gatekeeper-controlplane
       docker push ghcr.io/erikbos/gatekeeper-testbackend

  deploy:
    name: Deploy containers

    needs: build

    runs-on: ubuntu-latest
    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.14'

    - name: Set context
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Kubectl rollout restart
      run: |
        kubectl version

        kubectl rollout restart deployment/managementserver
        kubectl rollout restart deployment/accesslogserver
        kubectl rollout restart deployment/authserver
        kubectl rollout restart deployment/controlplane
        kubectl rollout restart deployment/testbackend

        kubectl get pods
