name: Build pipeline

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build containers

    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: actions-contrib/golangci-lint@v1

    - name: Build Docker images
      run: make docker-images

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.acr_hostname }}
        username: ${{ secrets.acr_username }}
        password: ${{ secrets.acr_password }}

    - name: put git version in env
      run: |
       echo "VERSION=`git describe --tags --always --dirty`" >> $GITHUB_ENV

    - name: Docker tag & push
      run: |
       echo ${{ github.sha }}
       echo $VERSION

       docker tag gatekeeper/dbadmin:$VERSION ${{ secrets.acr_hostname }}/dbadmin
       docker tag gatekeeper/envoyals:$VERSION ${{ secrets.acr_hostname }}/envoyals
       docker tag gatekeeper/envoyauth:$VERSION ${{ secrets.acr_hostname }}/envoyauth
       docker tag gatekeeper/envoycp:$VERSION ${{ secrets.acr_hostname }}/envoycp
       docker tag gatekeeper/testbackend:$VERSION ${{ secrets.acr_hostname }}/testbackend

       docker push ${{ secrets.acr_hostname }}/dbadmin
       docker push ${{ secrets.acr_hostname }}/envoyals
       docker push ${{ secrets.acr_hostname }}/envoyauth
       docker push ${{ secrets.acr_hostname }}/envoycp
       docker push ${{ secrets.acr_hostname }}/testbackend

  deploy:
    name: Deploy containers

    needs: build

    runs-on: ubuntu-latest
    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.14'

    - name: Set context
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Kubectl rollout restart
      run: |
        kubectl version

        kubectl rollout restart deployment/dbadmin
        kubectl rollout restart deployment/envoyals
        kubectl rollout restart deployment/envoyauth
        kubectl rollout restart deployment/envoycp
        kubectl rollout restart deployment/testbackend

        kubectl get pods
