name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: actions-contrib/golangci-lint@v1

    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    - name: Build Docker images
      run: make docker-images

    - name: Docker Login
      uses: azure/docker-login@v1
      with: 
        login-server: testerbs.azurecr.io
        username: ${{ secrets.acr_username }}
        password: ${{ secrets.acr_password }}

    - name: put git version in env
      run: echo ::set-env name=VERSION::$(git describe --tags --always --dirty)

    - name: Docker tag & push
      run: |
       echo ${{ github.sha }}
       echo $VERSION

       VERSION = $(git describe --tags --always --dirty)
       docker tag apiedge/dbadmin:$VERSION testerbs.azurecr.io/dbadmin
       docker tag apiedge/envoyauth:$VERSION testerbs.azurecr.io/envoyauth
       docker tag apiedge/envoycp:$VERSION testerbs.azurecr.io/envoycp
       docker push testerbs.azurecr.io/dbadmin
       docker push testerbs.azurecr.io/envoyauth
       docker push testerbs.azurecr.io/envoycp
       
