name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: actions-contrib/golangci-lint@v1

    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    - name: Build Docker images
      run: make docker-images
