name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: actions-contrib/golangci-lint@v1

    - name: Build Docker images
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
