name: Build pipeline

on:
  push:
    branches: [ master ]

jobs:
  build_containers:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: actions-contrib/golangci-lint@v1

    - name: Build Docker images
      run: make docker-images

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.acr_hostname }}
        username: ${{ secrets.acr_username }}
        password: ${{ secrets.acr_password }}

    - name: put git version in env
      run: echo ::set-env name=VERSION::$(git describe --tags --always --dirty)

    - name: Docker tag & push
      run: |
       echo ${{ github.sha }}
       echo $VERSION

       docker tag apiedge/dbadmin:$VERSION ${{ secrets.acr_hostname }}/dbadmin
       docker tag apiedge/envoyauth:$VERSION ${{ secrets.acr_hostname }}/envoyauth
       docker tag apiedge/envoycp:$VERSION ${{ secrets.acr_hostname }}/envoycp
       docker tag apiedge/testbackend:$VERSION ${{ secrets.acr_hostname }}/testbackend

       docker push ${{ secrets.acr_hostname }}/dbadmin
       docker push ${{ secrets.acr_hostname }}/envoyauth
       docker push ${{ secrets.acr_hostname }}/envoycp
       docker push ${{ secrets.acr_hostname }}/testbackend
