name: Build, test, e2e test PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - "docs/**"
    - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Set GOPATH and PATH
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run Go generate
        run: make generate-files

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: medyagh/setup-minikube@master
        id: minikube
        with:
          memory: 4000m

      - uses: azure/setup-helm@v1
        id: install

      - name: Run e2e test
        run: |
          make e2e-actions
