name: Unit tests and coverage report
on:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/'
    - "docs/**"
    - 'README.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '.github/'
    - "docs/**"
    - 'README.md'

jobs:
  test:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Prep Go environment to set GOPATH
      uses: actions/setup-go@v3

    - name: Lint Go code
      run: make lint

    - name: Run unit tests
      run: make test

    - name: Upload coverage to Codecov (managementserver)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: cmd/managementserver/
        flags: managementserver

    - name: Upload coverage to Codecov (accesslogserver)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: cmd/accesslogserver/
        flags: accesslogserver

    - name: Upload coverage to Codecov (authserver)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: cmd/authserver/
        flags: authserver

    - name: Upload coverage to Codecov (controlplane)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: cmd/controlplane/
        flags: controlplane

    - name: Upload coverage to Codecov (pkg)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: pkg/
        flags: pkg
