name: Unit tests and coverage report
on:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/'
    - "docs/**"
    - 'README.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '.github/'
    - "docs/**"
    - 'README.md'

jobs:
  test:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Golang CI lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29

    - name: Run unit tests
      run: make test

    - name: Upload coverage to Codecov (dbadmin)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: cmd/dbadmin/
        flags: dbadmin

    - name: Upload coverage to Codecov (envoyals)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: cmd/envoyals/
        flags: envoyals

    - name: Upload coverage to Codecov (envoyauth)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: cmd/envoyauth/
        flags: envoyauth

    - name: Upload coverage to Codecov (envoycp)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: cmd/envoycp/
        flags: envoycp

    - name: Upload coverage to Codecov (pkg)
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tmp/coverage.txt
        directory: pkg/
        flags: pkg
