name: Unit tests and coverage report
on:
  push:
    branches:
    - master
    paths-ignore:
    - '.github/'
    - "docs/**"
    - 'README.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.github/'
    - "docs/**"
    - 'README.md'

jobs:
  test:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Golang CI lint
      uses: actions-contrib/golangci-lint@v1

    - name: Run unit tests
      run: make testcoverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        yml: .codecov.yml
        file: tmp/coverage.txt
