---
apiVersion: v1
kind: Service
metadata:
  name: ratelimiter
spec:
  selector:
    app: ratelimiter
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: ratelimiter-grpc
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ratelimiter-http
    - protocol: TCP
      port: 6070
      targetPort: 6070
      name: ratelimiter-debug
